apiVersion: v1
kind: Service
metadata:
  name: jaeger-service-udp
  labels:
    app: jaeger
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  selector:
    app: jaeger
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  ports:
  - name: 5775-to-5775-udp
    port: 5775
    targetPort: 5775
    protocol: UDP
  - name: 6831-to-6831-udp
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: 6832-to-6832-udp
    port: 6832
    targetPort: 6832
    protocol: UDP
